######### Tournament REST API #########
GET http://localhost:8080/api/tournament

###
GET http://localhost:8080/api/tournament/3

###
GET http://localhost:8080/api/tournament/organizer/1

###
GET http://localhost:8080/api/tournament/search?searchTerm=olympics

###
GET http://localhost:8080/api/tournament/filter?startDate=2024-08-01&endDate=2024-10-31

###
GET http://localhost:8080/api/tournament/matching?isRandom=true

###
GET http://localhost:8080/api/tournament/sorted?sortBy=name&order=desc
# GET http://localhost:8080/api/tournament/sorted?sortBy=date&order=desc

###
POST http://localhost:8080/api/tournament
Content-Type: application/json
# Authorization: Basic admin goodpassword
{
    "name": "Summer Games",
    "location": "Stadium A",
    "date": "2024-07-01",
    "time": "14:30:00",
    "description": "Annual summer tournament.",
    "isRandom": true,
    "organizer_id": 1
}

###
PUT http://localhost:8080/api/tournament/1
Content-Type: application/json
{
    "name": "Summer Games",
    "location": "National Stadium",
    "date": "2024-07-01",
    "time": "14:30:00",
    "description": "Annual summer tournament.",
    "isRandom": true,
    "organizer_id": 1
}

###
DELETE http://localhost:8080/api/tournament
[1, 2, 3]


######### Duel REST API #########
###
GET http://localhost:8080/api/duel

###
GET http://localhost:8080/api/duel?tid=2

###
GET http://localhost:8080/api/duel/3

###
GET http://localhost:8080/api/duel/round?roundName=Quarter Finals

###
GET http://localhost:8080/api/duel/player?pid=5

###
POST http://localhost:8080/api/duel
Content-Type: application/json
Authorization: Basic admin goodpassword
{
    "pid1": 101,
    "pid2": 102,
    "roundName": "Quarter Finals",
    "tournament": {
        "tournament_id": 1
    }
}

###
PUT http://localhost:8080/api/duel/4
Content-Type: application/json
{
    "pid1": 101,
    "pid2": 102,
    "roundName": "Quarter Finals II",
    "tournament": {
        "tournament_id": 1
    }
}

###
PUT http://localhost:8080/api/duel/4/result
Content-Type: application/json
{
    "player1Time": 4567,
    "player2Time": 2345
}

###
DELETE http://localhost:8080/api/duel/3