name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - ci-cd
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd backend
          mvn -B package --file pom.xml -DskipTests

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t spring-boot-app .

      - name: Run Spring Boot Docker Container
        env:
          DB_URL: jdbc:mysql://localhost:3306/test_db
          DB_USERNAME: test_user
          DB_PASSWORD: test_password
        run: |
          docker run -d --name spring-boot-app \
            -e SPRING_DATASOURCE_URL=$DB_URL \
            -e SPRING_DATASOURCE_USERNAME=$DB_USERNAME \
            -e SPRING_DATASOURCE_PASSWORD=$DB_PASSWORD \
            -p 8080:8080 spring-boot-app

      - name: Wait for Spring Boot to start
        run: sleep 30

      - name: Run Integration Tests with Maven
        run: |
          cd backend
          mvn -B verify

      - name: Clean up Docker Container
        run: |
          docker stop spring-boot-app
          docker rm spring-boot-app