name: Java CI with Maven and External Database

on:
  push:
    branches:
      - main  
      - ci-test
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "AWS credentials set."

      - name: Build and Test with Maven
        working-directory: ./backend
        run: |
          mvn clean install -DskipTests  # Build the application
          mvn clean test -Dspring.profiles.active=ci  # Run tests with the 'ci' profile
