name: Java CI with Maven

on:
  push:
    branches:
      - main
      - ci-cd-integration

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up SSH tunnel to MySQL
        env:
          SSH_KEY: ${{ secrets.EC2_KEY }}
          BASTION_HOST: ${{ secrets.EC2_BACKEND_HOST }}
          MYSQL_PRIVATE_HOST: ${{ secrets.EC2_MYSQL_HOST }}
          MYSQL_PORT: "3306"
        run: |
          echo "$SSH_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -N -L 3306:$MYSQL_PRIVATE_HOST:$MYSQL_PORT -i ssh_key -o "StrictHostKeyChecking=no" ec2-user@$BASTION_HOST &

      - name: Build with Maven
        env:
          DB_URL: ${{ secrets.MYSQL_URL }}  # Pass the DB_URL secret
          DB_USERNAME: ${{ secrets.MYSQL_DATABASE }}  # Pass the DB_USERNAME secret
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}  # Pass the DB_PASSWORD secret
        run: mvn -B package --file backend/pom.xml
