name: Java CI with Maven and External Database

on:
  push:
    branches:
      - main  
      - ci-test
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set MySQL Connection Environment Variables
        env:
          DB_URL: ${{ secrets.TEST_MYSQL_URL }}
          DB_USERNAME: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: echo "Environment variables for MySQL set"

      - name: Build with Maven
        working-directory: ./backend  # Specify the backend folder
        run: |
          mvn clean install -DskipTests  # Build the application

      - name: Test with Maven
        working-directory: ./backend  # Specify the backend folder
        run: |
          mvn test  # Run the tests