name: Deploy SQL to EC2 MySQL

on:
  push:
    branches:
      - main
      - ci-cd-integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Copy SQL files to EC2 Bastion Host
        run: |
          # Copy SQL files to the Bastion Host (public EC2 instance)
          scp -o StrictHostKeyChecking=no -r backend/src/main/resources/sql/sqldump.sql ${{ secrets.EC2_GENERAL_USER }}@${{ secrets.EC2_BACKEND_HOST }}:/tmp

      - name: Create Database and Execute SQL files on EC2 MySQL through Bastion Host
        run: |
          # SSH into the Bastion Host (public EC2 instance) and execute SQL files on the MySQL server
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_GENERAL_USER }}@${{ secrets.EC2_BACKEND_HOST }} << 'EOF'
            # Create the database if it doesn't already exist
            echo "Creating database if it does not exist..."
            mysql -u "${{ secrets.MYSQL_USER }}" -p"${{ secrets.MYSQL_PASSWORD }}" -h "${{ secrets.EC2_MYSQL_HOST }}" -P "${{ secrets.MYSQL_PORT }}"

            # Execute the SQL dump file
            echo "Executing /tmp/sqldump.sql on the database"
            mysql -u "${{ secrets.MYSQL_USER }}" -p"${{ secrets.MYSQL_PASSWORD }}" -h "${{ secrets.EC2_MYSQL_HOST }}" -P "${{ secrets.MYSQL_PORT }}" "${{ secrets.MYSQL_DATABASE }}" < "/tmp/sqldump.sql"
            if [ $? -ne 0 ]; then
              echo "Error: Failed to execute /tmp/sqldump.sql"
              exit 1
            fi
          EOF

      - name: Notify success
        run: echo "SQL Deployment Successful!"
